# YAML
# YAML是一种标记语言 他以数据为中心 适合做配置文件
#
# YAML语法
#
# KEY:(空格)VALUE --- 表示键值对
# 以空格缩减控制层级关系 左对齐的一列数据都是同一层级
# YAML语法中属性和值都是大小写敏感的
#
#  值的表示
#
#  字面量(数值 字符串 布尔值)
#  字符串不加单引号或双引号
#  若字符串加双引号，其中特殊字符不会被转义
#  若字符串加单引号，其中特殊字符会被转义
#
#  对象/MAP
#  key : value 的形式表示
#  friend:
#    lastName: jerry
#   age: 20
#  或
#  friend : {lastName: jerry,age: 20}
#
#  数组
#  pets:
#      -(空格)cat
#      -(空格)dog
#  或
#  pets:[cat,dog]

#######################################################################################
#person:
#  name: jerry
#  age: 80
#  boss: false
#  birthday: 1940/11/05
#  car:
#    brand: BMW(宝马)
#    age: 60
#  chronicleOfEvents: {1999-01-01: up,2011-01-01: winning}
#  pets:
#    - cat:
#      name: kitty
#      birthday: 2010/01/01
#    - dog:
#      name: spike
#      birthday: 2010/01/01
#######################################################################################
server:
  port: 80

