#yaml配置文件支持文档块
#激活指定profile
#  1、在配置文件中指定 spring.profiles.active=ydev
#  2、命令行： java -jar spring-boot-1.0-SNAPSHOT.jar --spring.profiles.active=ydev；
#     可以直接在测试的时候，配置传入命令行参数
#  3、虚拟机参数； -Dspring.profiles.active=ydev

server:
  port: 8088

debug: false

spring:
  profiles:
    active: ydev
logging:
  level:
    root: DEBUG
---
#server:
  #port: 8080

spring:
  profiles: ydev
  messages:
    basename: i18n/message
  thymeleaf:
    cache: false
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 8
      min-idle: 1
      max-active: 20
      max-wait: 60000
      time-between-eviction-runsMillis: 60000
      min-evictable-idle-timeMillis: 300000
      validation-query: select 'x' FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      use-global-data-source-stat: true
      stat-view-servlet:
        enabled: true
        urlPattern: /druid/*
        login-username: druid
        login-password: root
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sample?useSSL=false&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root
    schema: classpath:sql/schema-mysql.sql
    data: classpath:sql/data-mysql.sql
    initializationMode: NEVER
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

mybatis:
  mapper-locations: "classpath*:org/mac/explorations/framework/springboot/web/repository/mybatis/xml/*.mapper.xml"
  configuration:
    map-underscore-to-camel-case: true
---
server:
  port: 8085
spring:
  profiles: yprod